# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Insert Heads
      run: |
        python travisPorcess.py
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'
    - name: Build Pages
      run: |
        bash build.sh
    - name: Publish Pages
      run: |
        git config user.name "Github Action"
        git config user.email "yindaheng98@163.com"
        git init
        git add -A
        git commit -m 'Github Action Deploy'
        git push -u https://${{ secrets.GITHUB_TOKEN }}@github.com/yindaheng98/yindaheng98.github.io.git HEAD:master --force
