# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Insert Heads
      run: |
        python travisPorcess.py
    - name: Prepare Theme
      run: |
        rm -rf .git
        git clone -b master https://github.com/yindaheng98/vuepress-blog.git ./theme
        cp -r 学习笔记/. ./theme/blogs
        cp -r 学习笔记/. ./theme/blogs/.vuepress/public
        cp -r ./theme/. ./
        rm -rf 学习笔记
        rm -rf theme
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'
    - name: Build Pages
      run: |
        npm install
        npm run build
        touch ./public/.nojekyll
    - name: Publish Pages
      working-directory: ./public
      run: |
        git config --global user.name "Github Action"
        git config --global user.email "yindaheng98@163.com"
        git init
        git add -A
        git commit -m 'Github Action Deploy'
        git push -u https://${{ secrets.GH_TOKEN }}@github.com/yindaheng98/yindaheng98.github.io.git HEAD:master --force
